service: hello-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
  stage: dev

package:
  patterns:
    - '!./**'
    - 'handler.js'
    - '!node_modules/**'
    - '!src/**'
    - '!bin/**'
    - '!lib/**'
    - '!.next/**'
    - '!cdk.out/**'

custom:
  s3Bucket: ${self:service}-frontend-${self:provider.stage}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true

resources:
  Resources:
    FrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3Bucket}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: 404.html

    FrontendBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref FrontendBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource: !Join ['', ['arn:aws:s3:::', !Ref FrontendBucket, '/*']]
